#!/usr/bin/env sh

set -e

exec 3>&1
exec 1>&2

REQ=$(cat -)

URI=$(echo $REQ | jq --raw-output .source.api_server_uri)
NS=$(echo $REQ | jq --raw-output .source.namespace)
CA=$(echo $REQ | jq --raw-output .source.certificate_authority_data)
TOKEN=$(echo $REQ | jq --raw-output .source.token)
CMDLINE=$(echo $REQ | jq --raw-output .params.cmdline)

cd "/tmp/build/put/"

/opt/kubectl config set-cluster cluster1 --server=$URI
/opt/kubectl config set-context context1 --cluster=cluster1 --user=user1 --namespace=$NS
/opt/kubectl config set clusters.cluster1.certificate-authority-data $CA
/opt/kubectl config set-credentials user1 --token=$TOKEN
/opt/kubectl config use-context context1

/opt/kubectl $CMDLINE

RESULT='{"version": {"value": "na"}, "metadata": [{"cmdline": "value-cmdline"}]}'
RESULT=$(echo $RESULT | jq ".metadata[0].cmdline=\"$CMDLINE\"")
echo $RESULT >&3 
